
package ws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChatImplService", targetNamespace = "http://services.ws/", wsdlLocation = "http://localhost:9999/chat-service?wsdl")
public class ChatImplService
    extends Service
{

    private final static URL CHATIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHATIMPLSERVICE_EXCEPTION;
    private final static QName CHATIMPLSERVICE_QNAME = new QName("http://services.ws/", "ChatImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/chat-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHATIMPLSERVICE_WSDL_LOCATION = url;
        CHATIMPLSERVICE_EXCEPTION = e;
    }

    public ChatImplService() {
        super(__getWsdlLocation(), CHATIMPLSERVICE_QNAME);
    }

    public ChatImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHATIMPLSERVICE_QNAME, features);
    }

    public ChatImplService(URL wsdlLocation) {
        super(wsdlLocation, CHATIMPLSERVICE_QNAME);
    }

    public ChatImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHATIMPLSERVICE_QNAME, features);
    }

    public ChatImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChatImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChatInterface
     */
    @WebEndpoint(name = "ChatImplPort")
    public ChatInterface getChatImplPort() {
        return super.getPort(new QName("http://services.ws/", "ChatImplPort"), ChatInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChatInterface
     */
    @WebEndpoint(name = "ChatImplPort")
    public ChatInterface getChatImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws/", "ChatImplPort"), ChatInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHATIMPLSERVICE_EXCEPTION!= null) {
            throw CHATIMPLSERVICE_EXCEPTION;
        }
        return CHATIMPLSERVICE_WSDL_LOCATION;
    }

}
